use_frameworks!

platform :ios, '13.0'

target 'ZHHAnimatedNumberLabel_Example' do
  pod 'ZHHAnimatedNumberLabel', :path => '../'
  pod 'ZHHAnneKit'

  target 'ZHHAnimatedNumberLabel_Tests' do
    inherit! :search_paths

    
  end
end
